import math
import pandas as pd
import numpy as np


def inst_to_ann(r):
    """Converts an instantaneous interest rate to an annualized rate."""
    return np.expm1(r)


def ann_to_inst(r):
    """Converts an annualized interest rate to an instantaneous rate."""
    return np.log1p(r)


def discount(t, r):
    """
    Computes the price of a pure discount bond paying $1 at time t,
    given per-period interest rate r.
    Returns a DataFrame indexed by t.
    """
    discounts = pd.DataFrame([(r + 1) ** -i for i in t])
    discounts.index = t
    return discounts


def pv(flows, r):
    """
    Computes the present value of a sequence of cash flows.
    flows is indexed by time period; r is the per-period discount rate.
    """
    dates = flows.index
    discounts = discount(dates, r)
    return discounts.multiply(flows, axis='rows').sum()


def funding_ratio(assets, liabilities, r):
    """
    Computes the funding ratio of a series of liabilities given an interest rate.
    """
    return pv(assets, r) / pv(liabilities, r)


def bond_cash_flows(maturity, principal=100, coupon_rate=0.03, coupons_per_year=12):
    """
    Returns the series of cash flows generated by a bond,
    indexed by the payment/coupon number.
    """
    n_coupons = round(maturity * coupons_per_year)
    coupon_amt = principal * coupon_rate / coupons_per_year
    coupon_times = np.arange(1, n_coupons + 1)
    cash_flows = pd.Series(data=coupon_amt, index=coupon_times)
    cash_flows.iloc[-1] += principal
    return cash_flows


def bond_price(maturity, principal=100, coupon_rate=0.03,
               coupons_per_year=12, discount_rate=0.03):
    """
    Computes the price of a bond that pays regular coupons until maturity.
    If discount_rate is a DataFrame, computes price over time.
    """
    if isinstance(discount_rate, pd.DataFrame):
        pricing_dates = discount_rate.index
        prices = pd.DataFrame(index=pricing_dates, columns=discount_rate.columns)
        for t in pricing_dates:
            prices.loc[t] = bond_price(
                maturity - t / coupons_per_year, principal,
                coupon_rate, coupons_per_year, discount_rate.loc[t]
            )
        return prices
    else:
        if maturity <= 0:
            return principal + principal * coupon_rate / coupons_per_year
        cash_flows = bond_cash_flows(maturity, principal, coupon_rate, coupons_per_year)
        return pv(cash_flows, discount_rate / coupons_per_year)


def macaulay_duration(flows, discount_rate):
    """
    Computes the Macaulay Duration of a sequence of cash flows
    given a per-period discount rate.
    """
    discounted_flows = discount(flows.index, discount_rate) * pd.DataFrame(flows)
    weights = discounted_flows / discounted_flows.sum()
    return np.average(flows.index, weights=weights.iloc[:, 0])


def match_durations(cf_t, cf_s, cf_l, discount_rate):
    """
    Returns the weight W in cf_s that, along with (1-W) in cf_l,
    matches the duration of cf_t.
    """
    d_t = macaulay_duration(cf_t, discount_rate)
    d_s = macaulay_duration(cf_s, discount_rate)
    d_l = macaulay_duration(cf_l, discount_rate)
    return (d_l - d_t) / (d_l - d_s)


def bond_total_return(monthly_prices, principal, coupon_rate, coupons_per_year):
    """
    Computes the total return of a bond based on monthly prices and coupon payments.
    Assumes coupons are reinvested in the bond.
    """
    coupons = pd.DataFrame(
        data=0, index=monthly_prices.index, columns=monthly_prices.columns
    )
    t_max = monthly_prices.index.max()
    pay_date = np.linspace(
        12 / coupons_per_year, t_max,
        int(coupons_per_year * t_max / 12), dtype=int
    )
    coupons.iloc[pay_date] = principal * coupon_rate / coupons_per_year
    total_returns = (monthly_prices + coupons) / monthly_prices.shift() - 1
    return total_returns.dropna()
